(function(){
  const DIFF={easy:{label:'Leicht',base:100},medium:{label:'Mittel',base:150},hard:{label:'Schwer',base:220},master:{label:'Meisterfall',base:300}};
  const state={index:0,total:0,attempts:0,hints:0,streak:0,startedAt:0,locked:false,results:[]};
  const $=s=>document.querySelector(s);
  const scenes=window.KC_KITCHEN_DETECTIVE_SCENES||[];
  function scene(){return scenes[state.index];}
  function start(){state.startedAt=Date.now();state.attempts=0;state.hints=0;state.locked=false;render();}
  function render(){const s=scene();if(!s)return; $('#caseNo').textContent=`Fall ${state.index+1} / ${scenes.length}`;$('#caseTitle').textContent=s.title;$('#question').textContent=s.question;$('#difficulty').textContent=DIFF[s.difficulty].label;$('#score').textContent=state.total;$('#sceneImage').src=s.image;$('#sceneImage').alt=`Szene ${s.id}: ${s.title}`;$('#feedback').innerHTML='';$('#hintBox').innerHTML='';$('#breakdown').innerHTML=''; const a=$('#answers');a.innerHTML='';s.answers.forEach((t,i)=>{const b=document.createElement('button');b.className='answer';b.textContent=`${String.fromCharCode(65+i)} – ${t}`;b.onclick=()=>answer(i);a.appendChild(b)});updatePointsPreview();}
  function updatePointsPreview(){const s=scene(),d=DIFF[s.difficulty];$('#pointsInfo').textContent=`Grundwert ${d.base} · 1. Versuch +40 · 2. Versuch +15 · Fehlversuch −20 · Hinweis 1 −25 · Hinweis 2 −40 · Zeitbonus bis +30`;}
  function answer(i){if(state.locked)return;const s=scene();state.attempts++;if(i===s.correct){state.locked=true;state.streak++;const secs=(Date.now()-state.startedAt)/1000;const base=DIFF[s.difficulty].base;const attemptBonus=state.attempts===1?40:state.attempts===2?15:0;const missPenalty=Math.max(0,state.attempts-1)*20;const hintPenalty=state.hints===0?0:state.hints===1?25:65;const timeBonus=Math.max(0,Math.round(30-Math.max(0,secs-10)/2));const streakBonus=state.streak>0&&state.streak%5===0?50:0;const earned=Math.max(0,base+attemptBonus+timeBonus+streakBonus-missPenalty-hintPenalty);state.total+=earned;state.results.push({id:s.id,earned,attempts:state.attempts,hints:state.hints});$('#score').textContent=state.total;$('#feedback').innerHTML=`<strong>Richtig!</strong> ${s.solution}`;$('#breakdown').innerHTML=`<b>${earned} Punkte</b><br>Grundwert ${base} + Versuch ${attemptBonus} + Zeit ${timeBonus} + Serie ${streakBonus} − Fehlversuche ${missPenalty} − Hinweise ${hintPenalty}`;showClue();document.querySelectorAll('.answer')[i].classList.add('correct');$('#nextBtn').hidden=false;}else{state.streak=0;document.querySelectorAll('.answer')[i].classList.add('wrong');$('#feedback').textContent='Noch nicht. Sieh genauer hin oder nutze einen Hinweis.';}}
  function hint(){if(state.locked)return;const s=scene();if(state.hints>=2)return;state.hints++;$('#hintBox').textContent=`Hinweis ${state.hints}: ${s.hints[state.hints-1]}`;updatePointsPreview();}
  function showClue(){const c=scene().clue,box=$('#clueMarker');box.style.left=c.x+'%';box.style.top=c.y+'%';box.style.width=c.w+'%';box.style.height=c.h+'%';box.hidden=false;}
  function next(){if(state.index>=scenes.length-1){finish();return;}state.index++;$('#clueMarker').hidden=true;$('#nextBtn').hidden=true;start();}
  function finish(){const max=scenes.reduce((n,s)=>n+DIFF[s.difficulty].base+70,0);const pct=Math.round(state.total/max*100);$('#game').innerHTML=`<section class="finish"><h2>20 Fälle abgeschlossen</h2><p class="big">${state.total} Punkte</p><p>Leistungswert: ${pct}%</p><p>${rank(state.total)}</p><button onclick="location.reload()">Neu starten</button></section>`;}
  function rank(p){if(p>=5000)return 'Rang: Meisterdetektiv';if(p>=4000)return 'Rang: Kücheninspektor';if(p>=3000)return 'Rang: Spürnase';return 'Rang: Küchendetektiv';}
  $('#hintBtn').onclick=hint;$('#nextBtn').onclick=next;start();
})();