(function(){
  const DIFF={easy:{label:'Leicht',base:100},medium:{label:'Mittel',base:150},hard:{label:'Schwer',base:220},master:{label:'Meisterfall',base:300}};
  const MODES={thief:'Wer war der Dieb?',wrong_place:'Was stimmt hier nicht?',missing:'Was fehlt oder wurde verlegt?',liar:'Wer lügt?',logic:'Logikfall',combo:'Kombifall',spot_difference:'Finde die Fehler'};
  const state={index:0,total:0,attempts:0,hints:0,streak:0,startedAt:0,locked:false,results:[],foundDifferences:0,foundMap:{}};
  const $=s=>document.querySelector(s);
  const scenes=window.KC_KITCHEN_DETECTIVE_SCENES||[];
  function scene(){return scenes[state.index];}
  function start(){state.startedAt=Date.now();state.attempts=0;state.hints=0;state.locked=false;state.foundDifferences=0;state.foundMap={};render();}
  function render(){const s=scene();if(!s)return;const difficulty=DIFF[s.difficulty];$('#caseNo').textContent=`Fall ${state.index+1} / ${scenes.length}`;$('#caseTitle').textContent=s.title;$('#question').textContent=s.question;$('#difficulty').textContent=difficulty.label;$('#modeBadge').textContent=MODES[s.mode]||s.mode;$('#score').textContent=state.total;$('#feedback').innerHTML='';$('#hintBox').innerHTML='';$('#breakdown').innerHTML='';$('#nextBtn').hidden=true;$('#clueMarker').hidden=true;renderModeSpecificScene(s);renderAnswers(s);updatePointsPreview();}
  function renderModeSpecificScene(s){const isDiff=s.mode==='spot_difference';$('#singleScene').hidden=isDiff;$('#diffScene').hidden=!isDiff;$('#answers').hidden=isDiff;if(isDiff){renderDifferenceScene(s);}else{$('#sceneImage').src=s.image||'';$('#sceneImage').alt=`Szene ${s.id}: ${s.title}`;}}
  function renderAnswers(s){const a=$('#answers');a.innerHTML='';if(s.mode==='spot_difference')return;s.answers.forEach((t,i)=>{const b=document.createElement('button');b.className='answer';b.textContent=`${String.fromCharCode(65+i)} – ${t}`;b.onclick=()=>answer(i);a.appendChild(b)});}
  function renderDifferenceScene(s){$('#diffLeftImage').src=s.leftImage||'';$('#diffRightImage').src=s.rightImage||'';$('#diffCounter').textContent=`0 / ${s.differences.length} Unterschiede gefunden`;$('#diffHelp').textContent=`Schwierigkeit: ${DIFF[s.difficulty].label} · Ziel: ${s.differences.length} Unterschiede`;const left=$('#diffLeftMarkers'),right=$('#diffRightMarkers');left.innerHTML='';right.innerHTML='';left.onclick=e=>{if(e.target===left)differenceMiss();};right.onclick=e=>{if(e.target===right)differenceMiss();};s.differences.forEach((d,idx)=>{createHotspot(left,d.left,idx);createHotspot(right,d.right,idx);});}
  function createHotspot(container,box,idx){const b=document.createElement('button');b.type='button';b.className='hotspot';b.style.left=box.x+'%';b.style.top=box.y+'%';b.style.width=box.w+'%';b.style.height=box.h+'%';b.onclick=e=>{e.stopPropagation();markDifference(idx);};container.appendChild(b);}
  function markDifference(idx){const s=scene();if(state.locked||state.foundMap[idx])return;state.foundMap[idx]=true;state.foundDifferences++;const d=s.differences[idx];addFoundMarker($('#diffLeftMarkers'),d.left);addFoundMarker($('#diffRightMarkers'),d.right);$('#diffCounter').textContent=`${state.foundDifferences} / ${s.differences.length} Unterschiede gefunden`;if(state.foundDifferences===s.differences.length){finishDifferenceScene();}}
  function addFoundMarker(container,box){const m=document.createElement('div');m.className='diff-marker';m.style.left=box.x+'%';m.style.top=box.y+'%';m.style.width=box.w+'%';m.style.height=box.h+'%';container.appendChild(m);}
  function differenceMiss(){if(state.locked)return;state.attempts++;state.streak=0;$('#feedback').textContent='Dort ist kein Unterschied. Versuche es noch einmal.';$('#breakdown').textContent=`Aktuell: ${state.attempts} Fehlklick${state.attempts===1?'':'s'} · mögliche Abzüge werden bei der Endwertung berechnet.`;}
  function finishDifferenceScene(){const s=scene();state.locked=true;state.streak++;const secs=(Date.now()-state.startedAt)/1000;const base=s.basePoints||DIFF[s.difficulty].base;const completionBonus=s.differences.length>=10?70:s.differences.length>=8?50:35;const missPenalty=Math.max(0,state.attempts)*20;const hintPenalty=state.hints===0?0:state.hints===1?25:65;const timeBonus=Math.max(0,Math.round(30-Math.max(0,secs-15)/2));const streakBonus=state.streak>0&&state.streak%5===0?50:0;const earned=Math.max(0,base+completionBonus+timeBonus+streakBonus-missPenalty-hintPenalty);state.total+=earned;state.results.push({id:s.id,earned,attempts:state.attempts,hints:state.hints,mode:s.mode});$('#score').textContent=state.total;$('#feedback').innerHTML=`<strong>Alle Unterschiede gefunden!</strong> ${s.solution||'Sehr gut beobachtet.'}`;$('#breakdown').innerHTML=`<b>${earned} Punkte</b><br>Grundwert ${base} + Komplettbonus ${completionBonus} + Zeit ${timeBonus} + Serie ${streakBonus} − Fehlklicks ${missPenalty} − Hinweise ${hintPenalty}`;$('#nextBtn').hidden=false;}
  function updatePointsPreview(){const s=scene();if(!s)return;if(s.mode==='spot_difference'){const base=s.basePoints||DIFF[s.difficulty].base;$('#pointsInfo').textContent=`Grundwert ${base} · Komplettbonus ${s.differences.length>=10?'+70':s.differences.length>=8?'+50':'+35'} · Hinweis 1 −25 · Hinweis 2 zusätzlich −40 · Fehlklick −20 · Zeitbonus bis +30 · Serienbonus +50`;}else{const d=DIFF[s.difficulty];$('#pointsInfo').textContent=`Grundwert ${d.base} · 1. Versuch +40 · 2. Versuch +15 · Fehlversuch −20 · Hinweis 1 −25 · Hinweis 2 zusätzlich −40 · Zeitbonus bis +30`;}}
  function answer(i){if(state.locked)return;const s=scene();state.attempts++;if(i===s.correct){state.locked=true;state.streak++;const secs=(Date.now()-state.startedAt)/1000;const base=DIFF[s.difficulty].base;const attemptBonus=state.attempts===1?40:state.attempts===2?15:0;const missPenalty=Math.max(0,state.attempts-1)*20;const hintPenalty=state.hints===0?0:state.hints===1?25:65;const timeBonus=Math.max(0,Math.round(30-Math.max(0,secs-10)/2));const streakBonus=state.streak>0&&state.streak%5===0?50:0;const earned=Math.max(0,base+attemptBonus+timeBonus+streakBonus-missPenalty-hintPenalty);state.total+=earned;state.results.push({id:s.id,earned,attempts:state.attempts,hints:state.hints,mode:s.mode});$('#score').textContent=state.total;$('#feedback').innerHTML=`<strong>Richtig!</strong> ${s.solution}`;$('#breakdown').innerHTML=`<b>${earned} Punkte</b><br>Grundwert ${base} + Versuch ${attemptBonus} + Zeit ${timeBonus} + Serie ${streakBonus} − Fehlversuche ${missPenalty} − Hinweise ${hintPenalty}`;showClue();document.querySelectorAll('.answer')[i].classList.add('correct');$('#nextBtn').hidden=false;}else{state.streak=0;document.querySelectorAll('.answer')[i].classList.add('wrong');$('#feedback').textContent='Noch nicht. Sieh genauer hin oder nutze einen Hinweis.';}}
  function hint(){if(state.locked)return;const s=scene();if(state.hints>=2)return;state.hints++;$('#hintBox').textContent=`Hinweis ${state.hints}: ${(s.hints||[])[state.hints-1]||'Achte auf kleine Details.'}`;updatePointsPreview();}
  function showClue(){const s=scene();if(!s.clue)return;const c=s.clue,box=$('#clueMarker');box.style.left=c.x+'%';box.style.top=c.y+'%';box.style.width=c.w+'%';box.style.height=c.h+'%';box.hidden=false;}
  function next(){if(state.index>=scenes.length-1){finish();return;}state.index++;start();}
  function finish(){const max=scenes.reduce((n,s)=>s.mode==='spot_difference'?n+(s.basePoints||DIFF[s.difficulty].base)+100:n+DIFF[s.difficulty].base+70,0);const pct=Math.round(state.total/max*100);$('#game').innerHTML=`<section class="finish"><h2>${scenes.length} Fälle abgeschlossen</h2><p class="big">${state.total} Punkte</p><p>Leistungswert: ${pct}%</p><p>${rank(state.total)}</p><button onclick="location.reload()">Neu starten</button></section>`;}
  function rank(p){if(p>=6500)return 'Rang: Meisterdetektiv';if(p>=5000)return 'Rang: Kücheninspektor';if(p>=3500)return 'Rang: Spürnase';return 'Rang: Küchendetektiv';}
  $('#hintBtn').onclick=hint;$('#nextBtn').onclick=next;start();
})();